apiVersion: apps/v1
kind: Deployment
metadata:
  name: avanti-php-deployment
spec:
  selector:
    matchLabels:
      app: AvantiPHPDemo
    replicas: 2
    template:
      metadata:
        labels:
          app: AvantiPHPDemo
      spec:
        containers:
        - name: avanti-php-demo
          image: pugme/avanti-centos-php72
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: avanti-php-service
  lables:
    app: AvantiPHPDemo
spec:
  selector:
    app: AvantiPHPDemo
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    clusterIP: 10.32.0.62
    type: NodePort
